#!/usr/bin/env python3
"""Bounded mutation harness for the tool adapter foundation (gpos/tools/).

    python3 tests/mutate_tools.py [--jobs N] [--only TEXT]

Each mutation disables or weakens exactly one high-risk foundation invariant in a temporary copy of
the repository and runs tests/test_tool_foundation.py there. A mutation must make the suite fail
("CAUGHT"); one that leaves it green is "MISSED" and fails this harness. An anchor that no longer
exists is reported "NOT APPLIED" and also fails the harness, so the list cannot rot. The repository
itself is never modified.

The list is deliberately bounded to the invariants that protect authority, safety and evidence
meaning; it is not a general mutation framework.
"""

import argparse
import concurrent.futures
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import mutation_gate as gate

ROOT = Path(__file__).resolve().parent.parent

# (name, file, anchor, replacement)
MUTATIONS = [
    # --- authority: what a tool may claim
    ('HUMAN_EVIDENCE allowed from a tool', 'gpos/tools/evidence.py',
     '    if candidate.evidence_type in pol[FORBIDDEN_KEY]:\n        return None, [diag("EVIDENCE_TYPE_FORBIDDEN",',
     '    if False:\n        return None, [diag("EVIDENCE_TYPE_FORBIDDEN",'),
    ('HUMAN_EVIDENCE accepted at registration', 'gpos/tools/validation.py',
     '        if etype in pol["forbidden_evidence_types"]:', '        if False:'),
    ('HUMAN_EVIDENCE materialized into a record', 'gpos/tools/evidence.py',
     '    if candidate.evidence_type in pol[FORBIDDEN_KEY]:\n        return None, [f"{candidate.evidence_type} can never be materialized',
     '    if False:\n        return None, [f"{candidate.evidence_type} can never be materialized'),
    ('a record is materialized without a proven revision', 'gpos/tools/evidence.py',
     '    if not candidate.materializable:\n        return None, ["the candidate has no proven subject revision',
     '    if False:\n        return None, ["the candidate has no proven subject revision'),
    # --- evidence semantics
    ('evidence context compatibility skipped', 'gpos/tools/evidence.py',
     '    if not compatible(framework, candidate.evidence_type, candidate.capture_context):', '    if False:'),
    ('registry compatibility ignored at registration', 'gpos/tools/validation.py',
     '        if context not in reg["evidence_context_compatibility"][etype]:', '        if False:'),
    ('an unobserved capture context is accepted', 'gpos/tools/evidence.py',
     '    elif candidate.capture_context != execution_context:', '    elif False:'),
    ('derivation upgrades its source context', 'gpos/tools/evidence.py',
     '        if inherited != {candidate.capture_context}:', '        if False:'),
    ('derived artifacts lose their origin context', 'gpos/tools/artifacts.py',
     '        origin = sorted(origins)[0] if len(origins) == 1 else (None if origins else execution_context)',
     '        origin = execution_context'),
    ('dry run allowed to emit runtime evidence', 'gpos/tools/evidence.py',
     '    if dry_run and candidate.evidence_type not in pol[DRY_RUN_KEY]:', '    if False:'),
    ('a capability may offer evidence it never declared', 'gpos/tools/evidence.py',
     '    if pair not in capability.evidence_pairs():', '    if False:'),
    ('incomplete artifacts offered as evidence', 'gpos/tools/evidence.py',
     '    incomplete = [a for a in candidate.artifact_ids if not by_id[a].complete]',
     '    incomplete = []'),
    ('evidence from an unfinished execution is kept', 'gpos/tools/execution.py',
     '        if accepted is not None and complete:', '        if accepted is not None:'),
    # --- mutation semantics
    ('mutating capability runs without consent', 'gpos/tools/execution.py',
     '    if capability.mutating and not request.dry_run and not request.allow_mutation:', '    if False:'),
    ('a mutating capability may be declared read-only', 'gpos/tools/validation.py',
     '    if cap.mutating and cap.side_effect_scope in (None, "", "NONE"):', '    if False:'),
    ('a read-only capability may report a mutation', 'gpos/tools/execution.py',
     '    if outcome.mutation_performed and not capability.mutating:', '    if False:'),
    ('dry run may mutate', 'gpos/tools/execution.py',
     '    mutation = bool(outcome.mutation_performed) and capability.mutating and not dry_run',
     '    mutation = bool(outcome.mutation_performed)'),
    ('dry run may run an unsupported capability', 'gpos/tools/execution.py',
     '    if request.dry_run and not capability.dry_run_supported:', '    if False:'),
    # --- single writer
    ('single-writer declaration no longer required', 'gpos/tools/validation.py',
     '    if needs_writer and not cap.single_writer_required:', '    if False:'),
    ('single-writer lease never taken', 'gpos/tools/execution.py',
     '    if mode == "EXECUTION" and not request.dry_run:\n        lease, problems = _acquire(',
     '    if False:\n        lease, problems = _acquire('),
    ('lease conflict ignored', 'gpos/tools/leases.py',
     '        fd = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)',
     '        fd = os.open(path, os.O_CREAT | os.O_WRONLY, 0o600)'),
    ('an unreadable lease is treated as free', 'gpos/tools/leases.py',
     '    return data if data is not None else {"unreadable": True, "path": str(path)}', '    return None'),
    ("another owner's lease is released", 'gpos/tools/leases.py',
     '    if holder.get("owner_id") != lease.owner_id or holder.get("token") != lease.token:\n        return False',
     '    if False:\n        return False'),
    ('breaking a lease needs no reason', 'gpos/tools/leases.py',
     '    if not reason:\n        raise LeaseHeld("LEASE_INVALID", "breaking a lease requires an explicit reason")',
     '    if False:\n        raise LeaseHeld("LEASE_INVALID", "breaking a lease requires an explicit reason")'),
    # --- process safety
    ('shell execution enabled', 'gpos/tools/process.py',
     '                    "stdout": subprocess.PIPE, "stderr": subprocess.PIPE, "close_fds": True}',
     '                    "stdout": subprocess.PIPE, "stderr": subprocess.PIPE, "close_fds": True,\n                    "shell": False}  # shell=True would be here'),
    ('shell interpreters accepted as the executable', 'gpos/tools/process.py',
     '    if Path(exe).name.lower() in SHELL_EXECUTABLES:', '    if False:'),
    ('program-string flags accepted', 'gpos/tools/process.py',
     '        if arg in SHELL_PROGRAM_FLAGS:', '        if False:'),
    ('a relative executable is accepted', 'gpos/tools/process.py',
     '    if not Path(exe).is_absolute():', '    if False:'),
    ('cwd boundary removed', 'gpos/tools/process.py',
     '    reason = tp.unsafe_reason(scopes, spec.cwd, must_exist=True)\n    if reason:', '    reason = None\n    if reason:'),
    ('timeout ignored', 'gpos/tools/process.py', '        proc.wait(timeout=spec.timeout)', '        proc.wait()'),
    ('timeout policy bound removed', 'gpos/tools/capabilities.py',
     '        if requested > self.maximum:', '        if False:'),
    ('a timed-out execution reports success', 'gpos/tools/execution.py',
     '        if process.timed_out:\n            diagnostics.append(dg.make("EXECUTION_TIMEOUT",',
     '        if False:\n            diagnostics.append(dg.make("EXECUTION_TIMEOUT",'),
    ('a failing tool reports success', 'gpos/tools/execution.py',
     '    if failed:\n        diagnostics.append(dg.make("EXECUTION_FAILED",',
     '    if False:\n        diagnostics.append(dg.make("EXECUTION_FAILED",'),
    ('output capture bound removed', 'gpos/tools/process.py',
     '            room = limit - len(sink["data"])\n            if room > 0:\n                sink["data"] += chunk[:room]',
     '            sink["data"] += chunk'),
    ('secret redaction disabled', 'gpos/tools/redaction.py',
     '    for pattern, replacement in PATTERNS:\n        text, n = pattern.subn(replacement, text)\n        count += n',
     '    for pattern, replacement in PATTERNS:\n        n = 0\n        count += n'),
    ('environment values copied into provenance', 'gpos/tools/process.py',
     '        names = {name for name, _ in self.overrides} | set(self.recorded)\n        return {"inherited_names": sorted(self.inherit), "set_names": sorted(names)}',
     '        return {"inherited_names": sorted(self.inherit), "set_names": sorted(self.build())}'),
    # --- paths and artifacts
    ('artifact path escape allowed', 'gpos/tools/artifacts.py',
     '        reason = tp.unsafe_reason(scopes, spec.path)\n        if reason:', '        reason = None\n        if reason:'),
    ('symlink escape allowed', 'gpos/tools/paths.py',
     '            if os.path.islink(current):\n                return f"{path}: component {current} is a symlink"',
     '            if False:\n                return f"{path}: component {current} is a symlink"'),
    ('path traversal allowed', 'gpos/tools/paths.py',
     '    if _under(roots, _resolve_prefix(lexical)) is None:\n        return outside',
     '    if False:\n        return outside'),
    ('the record area becomes a write target', 'gpos/tools/artifacts.py',
     '        if tp.in_records(root, spec.path):', '        if False:'),
    ('artifact hash ignored', 'gpos/tools/artifacts.py',
     '        try:  # the foundation hashes the file; an adapter never supplies its own digest\n            digest, size = _measure(path)',
     '        try:  # the foundation hashes the file; an adapter never supplies its own digest\n            digest, size = "0" * 64, path.stat().st_size'),
    ('a missing artifact is recorded anyway', 'gpos/tools/artifacts.py',
     '        if not path.is_file():', '        if False and not path.is_file():'),
    # --- provenance and result integrity
    ('provenance adapter id dropped', 'gpos/tools/provenance.py',
     '            "gpos_version": self.gpos_version, "adapter_id": self.adapter_id,',
     '            "gpos_version": self.gpos_version, "adapter_id": None,'),
    ('unknown provenance values are invented', 'gpos/tools/provenance.py',
     '    def unknown(self):\n        return tuple(name for name in CALLER_SUPPLIED if getattr(self, name) is None)',
     '    def unknown(self):\n        return ()'),
    ('a blocking diagnostic no longer downgrades the status', 'gpos/tools/diagnostics.py',
     '    classes = {d.cls for d in diags}\n    for cls in SEVERITY:',
     '    classes = set()\n    for cls in SEVERITY:'),
    ('an adapter may re-point a candidate at another subject', 'gpos/tools/execution.py',
     '        subject_kind=request.subject.kind, subject_ref=request.subject.ref,\n        subject_revision=request.subject.revision,',
     '        subject_kind=candidate.subject_kind or request.subject.kind, subject_ref=candidate.subject_ref,\n        subject_revision=candidate.subject_revision,'),
    ('all failures collapse into one status', 'gpos/tools/diagnostics.py',
     'EXIT_FOR = {SUCCESS: 0, INVALID_REQUEST: 1, FAILED: 2, TIMED_OUT: 3, UNAVAILABLE: 4,\n            CONFLICT: 5, INCOMPATIBLE: 6, CANCELLED: 7, INTERNAL_ERROR: 8, OUTCOME_UNKNOWN: 9}',
     'EXIT_FOR = {SUCCESS: 0, INVALID_REQUEST: 1, FAILED: 1, TIMED_OUT: 1, UNAVAILABLE: 1,\n            CONFLICT: 1, INCOMPATIBLE: 1, CANCELLED: 1, INTERNAL_ERROR: 1, OUTCOME_UNKNOWN: 1}'),
    # --- registry, lifecycle and preconditions
    ('a test-only adapter may be a production adapter', 'gpos/tools/validation.py',
     '    if test_markers and not allow_test_only:', '    if False:'),
    ('duplicate adapter ids accepted', 'gpos/tools/registry.py',
     '        if descriptor.adapter_id in self._adapters:', '        if False:'),
    ('duplicate capability ids accepted', 'gpos/tools/validation.py',
     '        if cap.id in seen:', '        if False:'),
    ('an adapter without a probe may register', 'gpos/tools/registry.py',
     '            if impl is None or impl is getattr(model.ToolAdapter, name):', '            if False:'),
    ('execution proceeds without a READY tool', 'gpos/tools/execution.py',
     '        probe, problems = registry.ready(request.adapter_id, started_at)\n        if problems:',
     '        probe, problems = registry.ready(request.adapter_id, started_at)\n        if False:'),
    ('a probe exception escapes as a crash', 'gpos/tools/registry.py',
     '        except Exception as exc:  # an adapter defect must not escape as a subprocess traceback',
     '        except KeyboardInterrupt as exc:'),
    ('an invalid project no longer blocks execution', 'gpos/tools/execution.py',
     '    if not result.valid:', '    if False:'),
    ('unrelated routing readiness blocks every capability', 'gpos/tools/execution.py',
     '    if capability.requires_ready_routing:', '    if True:'),
    ('unknown request inputs accepted', 'gpos/tools/execution.py',
     '    unknown = sorted(set(request.inputs or {}) - set(capability.input_kinds))',
     '    unknown = []'),
    # --- hardening round: integrity gaps closed after the independent code review
    ('extra_provenance allowed to override foundation truth', 'gpos/tools/evidence.py',
     '        if name in FOUNDATION_OWNED_PROVENANCE:', '        if False:'),
    ('a caller may supply provenance the execution never observed', 'gpos/tools/evidence.py',
     '            if known is None:', '            if False:'),
    ('any provenance field accepted as a supplement', 'gpos/tools/evidence.py',
     '        if name not in SUPPLEMENTAL_PROVENANCE:', '        if False:'),
    ('candidate provenance no longer reaches the record', 'gpos/tools/evidence.py',
     '    for name in FOUNDATION_OWNED_PROVENANCE:\n        value = known.get(name)',
     '    for name in ():\n        value = known.get(name)'),
    ('project-less project_root becomes a filesystem scope', 'gpos/tools/execution.py',
     '        if request.project_root:\n            return None, [dg.make("INVALID_TOOL_REQUEST",',
     '        if False:\n            return None, [dg.make("INVALID_TOOL_REQUEST",'),
    ('nested project id lookup broken', 'gpos/tools/execution.py',
     '    project_id = record_set.project_id if record_set is not None else None',
     '    project_id = None'),
    ('provenance duration taken from the process again', 'gpos/tools/execution.py',
     '    finished_at, duration = clock.now(), round(clock.monotonic() - started, 6)',
     '    finished_at, duration = clock.now(), round(process.duration_seconds if process else 0.0, 6)'),
    ('the adapter establishes evidence freshness', 'gpos/tools/execution.py',
     '        generated_at=generated_at, provenance=provenance.to_dict(), materializable=False)',
     '        provenance=provenance.to_dict(), materializable=False)'),
    ('invalid subject vocabulary accepted', 'gpos/tools/execution.py',
     '        if subject.kind not in reg["gate_scope_kinds"]:', '        if False:'),
    ('empty subject reference accepted', 'gpos/tools/execution.py',
     '        if not isinstance(subject.ref, str) or not subject.ref.strip():', '        if False:'),
    ('invalid actor accepted', 'gpos/tools/execution.py',
     '        if actor.kind not in reg["actor_kinds"]:', '        if False:'),
    ('invalid target platform accepted', 'gpos/tools/execution.py',
     '    if request.target_platform is not None and request.target_platform not in reg["platforms"]:',
     '    if False:'),
    ('impossible expected evidence accepted', 'gpos/tools/execution.py',
     '    for pair in request.expected_evidence or ():', '    for pair in ():'),
    ('request vocabulary never checked', 'gpos/tools/execution.py',
     '    problems = vocabulary_problems(framework, request, capability)\n    if problems:',
     '    problems = vocabulary_problems(framework, request, capability)\n    if False:'),
    ('adapter metadata redaction bypassed', 'gpos/tools/execution.py',
     '    outcome, redacted, unsupported = _sanitize_outcome(outcome, adapter_id, cap_id)',
     '    redacted, unsupported = 0, []'),
    ('credential-named keys no longer redacted', 'gpos/tools/redaction.py',
     '            if CREDENTIAL_NAME.match(key.strip()) and isinstance(item, str):',
     '            if False:'),
    ('credential-named flags no longer redact their value', 'gpos/tools/redaction.py',
     '            flagged = isinstance(item, str) and bool(CREDENTIAL_NAME.match(item.strip()))',
     '            flagged = False'),
    ('unsupported result values are stringified', 'gpos/tools/redaction.py',
     '    raise UnsupportedValue(f"{type(value).__name__} is not a value a ToolResult can carry")',
     '    return str(value), 0'),
    ('probe text is not redacted', 'gpos/tools/registry.py',
     '        result = _sanitized_probe(result)', '        pass'),
    ('artifact kind declaration ignored', 'gpos/tools/artifacts.py',
     '        elif spec.kind not in declared:', '        elif False:'),
    ('unknown registry artifact kind accepted', 'gpos/tools/artifacts.py',
     '        if spec.kind not in registry_kinds:', '        if False:'),
    ('duplicate artifact ids allowed', 'gpos/tools/artifacts.py',
     '        if aid in seen:', '        if False:'),
    ('an output artifact may shadow an input', 'gpos/tools/artifacts.py',
     '        if aid in inputs:', '        if False:'),
    ('artifact claim problems no longer refuse the artifact', 'gpos/tools/execution.py',
     '    refused = {aid for _, aid, _ in claim_problems}', '    refused = set()'),
    ('lease release failure ignored', 'gpos/tools/execution.py',
     '    if lease_mod.release(root, lease):\n        return []', '    if True:\n        return []'),
    ('a stranded lease still reports the original status', 'gpos/tools/execution.py',
     '    if problems:  # the status is recomputed: a stranded lease is never a clean SUCCESS',
     '    if False:  # the status is recomputed: a stranded lease is never a clean SUCCESS'),
    ('project-root lease identity uses the raw path', 'gpos/tools/execution.py',
     '    return f"{capability.resource_kind}:{Path(root).resolve()}", None',
     '    return f"{capability.resource_kind}:{str(root).rstrip(chr(47))}", None'),
    ('a request-named resource is no longer required', 'gpos/tools/execution.py',
     '        if not isinstance(request.resource_id, str) or not request.resource_id.strip():',
     '        if False:'),
    ('a process-start failure is an opaque defect again', 'gpos/tools/process.py',
     '    except (FileNotFoundError, PermissionError, NotADirectoryError, IsADirectoryError) as exc:',
     '    except NotADirectoryError as exc:'),
    ('dry run creates its workspace anyway', 'gpos/tools/execution.py',
     '    if request.dry_run:\n        return tuple(scopes), workspace, []  # a dry run resolves the plan and creates nothing',
     '    if False:\n        return tuple(scopes), workspace, []  # a dry run resolves the plan and creates nothing'),
    ('the caller-named scope is created before it is checked', 'gpos/tools/execution.py',
     '            scopes.insert(0, tp.resolve_without_creating(workspace))',
     '            workspace.mkdir(parents=True, exist_ok=True)\n            scopes.insert(0, workspace.resolve())'),
    ('workspace creation failure escapes as an exception', 'gpos/tools/execution.py',
     '    except OSError as exc:\n        return [dg.make("WORKSPACE_NOT_USABLE",',
     '    except UnicodeError as exc:\n        return [dg.make("WORKSPACE_NOT_USABLE",'),
    ('an output path that is a regular file is not refused', 'gpos/tools/execution.py',
     '    if workspace.exists() and not workspace.is_dir():', '    if False:'),
    ('a relative output directory is accepted', 'gpos/tools/execution.py',
     '        if not workspace.is_absolute():', '        if False:'),
    # --- Phase-2C-1 amendment: the private raw capture channel
    ('raw capture accidentally serialized into the result', 'gpos/tools/execution.py',
     '        diagnostics=tuple(diagnostics), data=outcome.data, plan=tuple(outcome.plan))',
     '        diagnostics=tuple(diagnostics), plan=tuple(outcome.plan),\n'
     '        data={**(outcome.data or {}), "raw": process.raw_stdout.decode("utf-8", "replace") if process else ""})'),
    ('public stdout no longer redacted', 'gpos/tools/process.py',
     '    out, out_n = redact(raw_out.decode("utf-8", errors="replace"))',
     '    out, out_n = raw_out.decode("utf-8", errors="replace"), 0'),
    ('raw buffer bypasses the capture limit', [
        ('gpos/tools/process.py', '            sink["total"] += len(chunk)\n',
         '            sink["total"] += len(chunk)\n            sink.setdefault("all", bytearray()).extend(chunk)\n'),
        ('gpos/tools/process.py',
         '    raw_out, raw_err = bytes(sinks[0]["data"]), bytes(sinks[1]["data"])  # the bounded capture, unredacted',
         '    raw_out, raw_err = bytes(sinks[0].get("all", sinks[0]["data"])), bytes(sinks[1].get("all", sinks[1]["data"]))')]),
    ('raw capture shown in repr', 'gpos/tools/process.py',
     '    raw_stdout: bytes = field(default=b"", repr=False)', '    raw_stdout: bytes = field(default=b"")'),
    ('the CLI packs path and context into one ambiguous value', 'gpos/tools/cli.py',
     '        artifact_id, path = item.split("=", 1)', '        artifact_id, path = item.split(":", 1)'),
    ('the CLI accepts --build-revision but drops it', 'gpos/tools/cli.py',
     '        build_revision=args.build_revision, build_id=args.build_id,', '        build_revision=None, build_id=args.build_id,'),
    ('the CLI accepts --target-platform but drops it', 'gpos/tools/cli.py',
     '        target_platform=args.target_platform, device=args.device, session_id=args.session_id)',
     '        target_platform=None, device=args.device, session_id=args.session_id)'),
    ('the CLI drops --build-id', 'gpos/tools/cli.py',
     '        build_revision=args.build_revision, build_id=args.build_id,', '        build_revision=args.build_revision, build_id=None,'),
    ('the CLI drops --device', 'gpos/tools/cli.py',
     '        target_platform=args.target_platform, device=args.device, session_id=args.session_id)',
     '        target_platform=args.target_platform, device=None, session_id=args.session_id)'),
    # --- network semantics (Phase 2C-5): FORBIDDEN default, TOOL_INHERENT allowlisted and disclosed
    ('TOOL_INHERENT usable by any adapter', 'gpos/tools/validation.py',
     '    elif aid not in pol["network_semantic_adapters"].get(net, []):\n', '    elif False:\n'),
    ('TOOL_INHERENT without a disclosure', 'gpos/tools/validation.py', '    elif not disclosure:\n', '    elif False:\n'),
    ('FORBIDDEN may carry a disclosure', 'gpos/tools/validation.py',
     '        if disclosure:\n            _problem(out, aid, f"network {net!r} is the default', '        if False:\n            _problem(out, aid, f"network {net!r} is the default'),
    ('any network value accepted', 'gpos/tools/validation.py',
     '    if net not in pol["network_semantics"]:\n', '    if False:\n'),
    ('the TOOL_INHERENT allowlist names another adapter', 'core/registry.json',
     '"TOOL_INHERENT": [\n        "unity",\n        "player"\n      ]', '"TOOL_INHERENT": [\n        "unity",\n        "player",\n        "git"\n      ]'),
    ('a FORBIDDEN adapter silently becomes TOOL_INHERENT', [
        ('core/registry.json', '"TOOL_INHERENT": [\n        "unity",\n        "player"\n      ]', '"TOOL_INHERENT": [\n        "unity",\n        "player",\n        "git"\n      ]'),
        ('gpos/tools/git/adapter.py', 'supported_platforms=("MACOS", "LINUX", "WINDOWS"), capabilities=CAPABILITIES,',
         'supported_platforms=("MACOS", "LINUX", "WINDOWS"), capabilities=CAPABILITIES, network="TOOL_INHERENT", '
         'network_disclosure=("git may fetch",),')]),
    ('an execution request carries a network destination', 'gpos/tools/execution.py',
     '    request_id: str = None\n    session_id: str = None', '    request_id: str = None\n    registry_url: str = None\n    session_id: str = None'),
    # --- Phase 2C-6A: SESSION leases, lease modes, OUTCOME_UNKNOWN
    ('a SESSION lease is judged stale from the attaching command pid', 'gpos/tools/leases.py',
     '    if scope_of(record) != EXECUTION:  # the command that took a SESSION lease has long exited\n        return False\n', ''),
    ('a batch writer meeting a session gets the old conflict and stale report', 'gpos/tools/execution.py',
     '        if exc.code == "LEASE_CONFLICT" and lease_mod.scope_of(exc.holder) == lease_mod.SESSION:\n            # A live session',
     '        if False:\n            # A live session'),
    ('session verification ignores the owner', 'gpos/tools/leases.py',
     '    if owner_id is not None and record.get("owner_id") != owner_id:', '    if False:'),
    ('session verification ignores the session id', 'gpos/tools/leases.py',
     '    if bound.get("session_id") != session_id:', '    if False:'),
    ('the session owner drops the actor kind', 'gpos/tools/leases.py',
     '    owner = f"{actor.kind}:{actor.id}"', '    owner = f"AGENT:{actor.id}"'),
    ('an opened but unconfirmed session outlives its execution', 'gpos/tools/execution.py',
     '        if self.opened is None or self.confirmed:\n            return []', '        if True:\n            return []'),
    ('a session id is accepted by a capability without sessions', 'gpos/tools/execution.py',
     '        if not capability.takes_session_id:\n            out.append(f"{cap} names no existing session, so a session_id has no meaning for it")',
     '        if False:\n            out.append(f"{cap} names no existing session, so a session_id has no meaning for it")'),
    ('a session capability runs without a session id', 'gpos/tools/execution.py',
     '    elif capability.takes_session_id:\n        out.append(f"{cap} acts on an existing session and needs session_id")', ''),
    ('a session capability runs without an owner', 'gpos/tools/execution.py',
     '    if capability.session_mode and lease_mod.session_owner(request.actor) is None:', '    if False:'),
    ('a lease break ignores the inspected token', 'gpos/tools/leases.py',
     '    if expected_token is not None and (record is None or record.get("token") != expected_token):', '    if False:'),
    ('SESSION_REQUIRED takes a writer lease (modes conflated)', 'gpos/tools/execution.py',
     '    if mode == "EXECUTION" and not request.dry_run:', '    if capability.single_writer_required and not request.dry_run:'),
    ('a capability reaches a lease operation of another mode', 'gpos/tools/execution.py',
     '        if self.capability.effective_lease_mode not in modes:\n            raise AssertionError', '        if False:\n            raise AssertionError'),
    ('a READ_ONLY capability may claim a writer lease to require a session', 'gpos/tools/validation.py',
     '    if mode == "SESSION_REQUIRED" and cap.mutating != cap.single_writer_required:', '    if False:'),
    ('a STATELESS capability may use a session', 'gpos/tools/validation.py',
     '    if cap.state_model != "STATEFUL":\n        _problem(out, adapter_id, f"{cap.id} uses a session, so it must be STATEFUL", cap.id)', ''),
    ('OUTCOME_UNKNOWN shares the FAILED exit code', 'gpos/tools/diagnostics.py',
     'INTERNAL_ERROR: 8, OUTCOME_UNKNOWN: 9}', 'INTERNAL_ERROR: 8, OUTCOME_UNKNOWN: 2}'),
    ('an unknown live outcome is reported as FAILED', 'gpos/tools/diagnostics.py',
     '    "LIVE_OUTCOME_UNKNOWN": (OUTCOME_UNKNOWN,', '    "LIVE_OUTCOME_UNKNOWN": (FAILED,'),
    # --- alpha.17: identity grammars match the whole string (a final LF or CRLF is refused)
    ('a session owner may end in a newline', 'gpos/tools/leases.py',
     '    return owner if SESSION_OWNER.fullmatch(owner) else None', '    return owner if SESSION_OWNER.match(owner) else None'),
    ('a SESSION lease owner may end in a newline', 'gpos/tools/leases.py',
     'or not SESSION_OWNER.fullmatch(owner_id):', 'or not SESSION_OWNER.match(owner_id):'),
    ('a SESSION lease id may end in a newline', 'gpos/tools/leases.py',
     'not SESSION_ID.fullmatch(str(session.get("session_id", ""))):', 'not SESSION_ID.match(str(session.get("session_id", ""))):'),
    ('a request session_id may end in a newline', 'gpos/tools/execution.py',
     'not lease_mod.SESSION_ID.fullmatch(request.session_id):', 'not lease_mod.SESSION_ID.match(request.session_id):'),
    ('an actor id may end in a newline', 'gpos/tools/execution.py',
     'not ACTOR_ID.fullmatch(actor.id or "")', 'not ACTOR_ID.match(actor.id or "")'),
    ('an adapter id may end in a newline', 'gpos/tools/validation.py',
     'not ID.fullmatch(aid or "")', 'not ID.match(aid or "")'),
    ('an adapter version may end in a newline', 'gpos/tools/validation.py',
     'not VERSION.fullmatch(descriptor.adapter_version or "")', 'not VERSION.match(descriptor.adapter_version or "")'),
    ('a capability id may end in a newline', 'gpos/tools/validation.py',
     'not ID.fullmatch(cap.id or "")', 'not ID.match(cap.id or "")'),
    ('an artifact id may end in a newline', 'gpos/tools/artifacts.py',
     'not ARTIFACT_ID.fullmatch(aid or "")', 'not ARTIFACT_ID.match(aid or "")'),
    # --- alpha.21: request-id path safety and capability-owned workspaces
    ('an unsafe request id reaches workspace resolution', 'gpos/tools/execution.py',
     '    if request.request_id is not None and not (isinstance(request.request_id, str)',
     '    if False and not (isinstance(request.request_id, str)'),
    ('a capability-owned workspace accepts a caller output_dir', 'gpos/tools/execution.py',
     '    if request.output_dir is not None and not capability.caller_output_dir_allowed:',
     '    if False:'),
    ('the output_dir rule is not inspectable', 'gpos/tools/capabilities.py',
     '                "caller_output_dir_allowed": self.caller_output_dir_allowed,\n', ''),
    ('a non-project capability may refuse every output_dir', 'gpos/tools/validation.py',
     '    elif not cap.caller_output_dir_allowed and not cap.requires_project:', '    elif False:'),
    ('the output_dir default is narrowed', 'gpos/tools/capabilities.py',
     '    caller_output_dir_allowed: bool = True', '    caller_output_dir_allowed: bool = False'),
    # --- alpha.22: the gated detached process and the allowlisted host location
    ('the detached-spawn gate is removed', 'gpos/tools/execution.py',
     '        if not (self.capability.detached_spawn and self.detached_allowed):', '        if False:'),
    ('more than one detached process per execution', 'gpos/tools/execution.py',
     '        if self._detached:\n            raise AssertionError("an execution starts at most one detached process")',
     '        if False:\n            raise AssertionError("an execution starts at most one detached process")'),
    ('a dry run may start a detached process', 'gpos/tools/execution.py',
     '        if self.dry_run:\n            raise AssertionError("a dry run starts no process")',
     '        if False:\n            raise AssertionError("a dry run starts no process")'),
    ('a detached spawn skips the boundary rules', 'gpos/tools/process.py',
     '    validate_spec(ToolProcessSpec(executable=spec.executable, argv=tuple(spec.argv), cwd=spec.cwd, env=spec.env),\n                  scopes)',
     '    pass'),
    ('a detached process shares the caller session', 'gpos/tools/process.py',
     '                                 close_fds=True, start_new_session=True)', '                                 close_fds=True, start_new_session=False)'),
    ('a detached process is never reaped', 'gpos/tools/process.py',
     '    threading.Thread(target=child.wait, daemon=True).start()   # reap it whenever it ends; never wait here\n', ''),
    ('registration ignores the detached-spawn allowlist', 'gpos/tools/validation.py',
     '    if cap.id not in pol["detached_spawn_capabilities"]:', '    if False:'),
    ('registration ignores the detached-spawn shape', 'gpos/tools/validation.py',
     '    if not (cap.effective_lease_mode == "SESSION_OPEN" and cap.single_writer_required and cap.requires_project\n            and cap.requires_tool):',
     '    if False:'),
    ('registration ignores the host-location allowlist', 'gpos/tools/validation.py',
     '    if cap.id not in pol["host_location_capabilities"].get(name, []):', '    if False:'),
    ('registration ignores the host-location shape', 'gpos/tools/validation.py',
     '    if not (cap.category == "DEPLOY" and cap.mutating and cap.requires_project):', '    if False:'),
    ('every execution gets the host location', 'gpos/tools/execution.py',
     '    if name is None:\n        return None\n    reg = framework.registry',
     '    if name is None:\n        return str(tp.host_location("USER_APPLICATIONS_GPOS"))\n    reg = framework.registry'),
    ('the execution does not re-check the host-location allowlist', 'gpos/tools/execution.py',
     '    if name not in reg["tool_host_locations"] or capability.id not in allowed:', '    if False:'),
    ('the host location follows HOME', 'gpos/tools/paths.py',
     '    return Path(pwd.getpwuid(os.getuid()).pw_dir)', '    return Path(os.environ["HOME"])'),
    ('the new capability fields are not inspectable', 'gpos/tools/capabilities.py',
     '                "detached_spawn": self.detached_spawn, "host_location": self.host_location,\n', ''),
    # --- alpha.23: process integrity at every boundary (host-neutral; tests V01, V02)
    ('an unproven outcome keeps a trustworthy exit code', 'gpos/tools/process.py',
     '    if not outcome.integrity_ok and outcome.exit_code is not None:', '    if False:'),
    ('the observer records nothing', 'gpos/tools/process.py', '        seen.append(outcome)\n', '        pass\n'),
    ('run_process bypasses the observer', 'gpos/tools/process.py',
     '    return _observed(backend(spec, scopes, clock))', '    return backend(spec, scopes, clock)'),
    ('integrity is always proven', 'gpos/tools/process.py',
     '        return self.tree_contained and self.capture_complete', '        return True'),
    ('the execution ignores an unproven process', 'gpos/tools/execution.py',
     '    if unsafe is not None:\n        # An unproven process', '    if False:\n        # An unproven process'),
    ('an uncontained tree is not diagnosed', 'gpos/tools/execution.py',
     '        if not outcome.tree_contained:\n            out.append(dg.make("PROCESS_TREE_NOT_CONTAINED",\n',
     '        if False:\n            out.append(dg.make("PROCESS_TREE_NOT_CONTAINED",\n'),
    ('an incomplete capture is not diagnosed', 'gpos/tools/execution.py',
     '        if not outcome.capture_complete:\n            out.append(dg.make("PROCESS_CAPTURE_INCOMPLETE",\n',
     '        if False:\n            out.append(dg.make("PROCESS_CAPTURE_INCOMPLETE",\n'),
    ('the execution is not observed', 'gpos/tools/execution.py',
     '    with proc.observe() as observed:\n        try:\n            outcome = adapter.execute(request, context)',
     '    observed = []\n    with proc.observe():\n        try:\n            outcome = adapter.execute(request, context)'),
    ('a probe ignores its own unproven processes', 'gpos/tools/registry.py',
     '        result = _with_integrity(adapter_id, result, observed)\n', ''),
    ('a probe reports a usable tool after an unproven process', 'gpos/tools/registry.py',
     '    return dataclasses.replace(result, status=model.UNAVAILABLE,', '    return dataclasses.replace(result,'),
    ('an adapter is probed on a platform it does not declare', 'gpos/tools/registry.py',
     '        if platform is None or platform not in adapter.descriptor.supported_platforms:\n            # alpha.23 (D12)',
     '        if False:\n            # alpha.23 (D12)'),
    ('an unrecognised host passes the platform gate again', 'gpos/tools/execution.py',
     '    if platform is None or platform not in adapter.descriptor.supported_platforms:   # alpha.23 (D12): fail closed',
     '    if platform is not None and platform not in adapter.descriptor.supported_platforms:'),
    ('a second Windows process facility appears', 'gpos/tools/paths_win32.py',
     'import ctypes\nimport msvcrt\n', 'import ctypes\nimport msvcrt\nimport subprocess\n'),
    ('a kernel32 function outside the allowlist is bound', 'gpos/tools/process_win32.py',
     '_bind("CloseHandle", wintypes.BOOL, wintypes.HANDLE)\n',
     '_bind("CloseHandle", wintypes.BOOL, wintypes.HANDLE)\n_bind("CreateRemoteThread", wintypes.HANDLE)\n'),
    ('foundation text I/O without an encoding', 'gpos/tools/leases.py',
     '        data = json.loads(Path(path).read_text(encoding="utf-8"))', '        data = json.loads(Path(path).read_text())'),
]

# --- alpha.23: the Windows mechanisms (tests/test_windows_foundation.py); NOT_RUN on any other host
P32, F32, L = 'gpos/tools/process_win32.py', 'gpos/tools/paths_win32.py', 'gpos/tools/leases.py'
DISCOVERY_GUARD = ('        if sys.platform == "win32":   # alpha.24: PATH only, never the current directory, only <name>.exe\n'
                   '            which = executables.windows_which if which is shutil.which else which\n')
WINDOWS_MUTATIONS = [
    ('the child is not created suspended', P32,
     'CREATION_FLAGS = (EXTENDED_STARTUPINFO_PRESENT | CREATE_UNICODE_ENVIRONMENT | CREATE_SUSPENDED\n',
     'CREATION_FLAGS = (EXTENDED_STARTUPINFO_PRESENT | CREATE_UNICODE_ENVIRONMENT\n'),
    ('the child is resumed before it is proven', P32, '        _hook("after_create", info, job)\n',
     '        _k32.ResumeThread(info.hThread)\n        _hook("after_create", info, job)\n'),
    ('job membership is not proven', P32,
     '        in_job = _in_job(info.hProcess, job) and not _hook("deny_membership")', '        in_job = True'),
    ('the image identity is not proven', P32, '        if not (in_job and pw.same_path(image, exe_final)):',
     '        if not in_job:'),
    ('the readers start after the child runs', P32,
     '            for reader in readers:\n                reader.start()\n            # Φ3 run\n            _hook("before_resume", info, readers)\n',
     '            # Φ3 run\n            _hook("before_resume", info, readers)\n'),
    ('descendants are left running when the root exits', P32,
     '            _k32.TerminateJobObject(job, TERMINATED_EXIT)\n            end = now() + CLEANUP_SECONDS\n',
     '            end = now() + CLEANUP_SECONDS\n'),
    ('containment is assumed, not observed', P32, '        result.tree_contained = active == 0',
     '        result.tree_contained = True'),
    ('an incomplete capture is reported complete', P32,
     '        result.capture_complete = not any(reader.is_alive() for reader in readers)',
     '        result.capture_complete = True'),
    ('the deadline restarts after creation', P32, '        _hook("after_create", info, job)\n',
     '        _hook("after_create", info, job)\n        deadline = now() + spec.timeout\n'),
    ('setup is not counted against the deadline', P32, '        _hook("setup_done")\n        if now() >= deadline:',
     '        _hook("setup_done")\n        deadline = now() + spec.timeout\n        if now() >= deadline:'),
    ('descendants may break away from the job', P32,
     'JOB_LIMITS = JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE | JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION',
     'JOB_LIMITS = JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE | JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION | 0x800'),
    ('every inheritable handle reaches the child', P32,
     '    for attribute, value in ((PROC_THREAD_ATTRIBUTE_HANDLE_LIST, handles), (PROC_THREAD_ATTRIBUTE_JOB_LIST, jobs)):',
     '    for attribute, value in ((PROC_THREAD_ATTRIBUTE_JOB_LIST, jobs),):'),
    ('the child is created outside the job', P32,
     '    for attribute, value in ((PROC_THREAD_ATTRIBUTE_HANDLE_LIST, handles), (PROC_THREAD_ATTRIBUTE_JOB_LIST, jobs)):',
     '    for attribute, value in ((PROC_THREAD_ATTRIBUTE_HANDLE_LIST, handles),):'),
    ('liveness signals the process again', L,
     '    if sys.platform == "win32":   # os.kill(pid, 0) is a console control event on Windows, never a probe\n'
     '        from . import process\n        return process.host_pid_alive(pid)\n', ''),
    ('a directory is opened through its reparse point', F32,
     '                 OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS | FILE_FLAG_OPEN_REPARSE_POINT)',
     '                 OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS)'),
    ('a pinned directory may be renamed', F32,
     '    return _open(path, FILE_LIST_DIRECTORY | FILE_READ_ATTRIBUTES | SYNCHRONIZE, FILE_SHARE_READ | FILE_SHARE_WRITE,',
     '    return _open(path, FILE_LIST_DIRECTORY | FILE_READ_ATTRIBUTES | SYNCHRONIZE, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE,'),
    ('the canonical spelling is not proven', F32, '    if not same_path(actual, str(lexical)):', '    if False:'),
    ("another owner's lease is released on Windows", L,
     'lambda r: r.get("owner_id") == lease.owner_id and r.get("token") == lease.token', 'lambda r: True'),
    ('the Windows deadline is not enforced', P32,
     '                state = _k32.WaitForSingleObject(info.hProcess, min(int(remaining * 1000) + 1, MAX_WAIT_MS))',
     '                state = _k32.WaitForSingleObject(info.hProcess, 0xFFFFFFFF)'),
    ('Windows environment values are copied into provenance', 'gpos/tools/process.py',
     '"set_names": sorted({name for name, _ in self.overrides} | set(self.recorded))}',
     '"set_names": sorted(self.build())}'),
    ('Windows containment is not checked', F32, '    if not any(within(r, target) for r in roots):', '    if False:'),
    ('a Windows process-start failure is an opaque defect again', P32,
     '    if err in (ERROR_FILE_NOT_FOUND, ERROR_PATH_NOT_FOUND, ERROR_ACCESS_DENIED, ERROR_BAD_EXE_FORMAT,',
     '    if False and err in (ERROR_FILE_NOT_FOUND, ERROR_PATH_NOT_FOUND, ERROR_ACCESS_DENIED, ERROR_BAD_EXE_FORMAT,'),
    ('Windows public stdout is no longer redacted', 'gpos/tools/process.py',
     '    out, out_n = redact(raw.raw_stdout.decode("utf-8", errors="replace"))',
     '    out, out_n = raw.raw_stdout.decode("utf-8", errors="replace"), 0'),
    ('the Windows raw buffer bypasses the capture limit', [
        ('gpos/tools/process.py', '            sink["total"] += len(chunk)\n',
         '            sink["total"] += len(chunk)\n            sink.setdefault("all", bytearray()).extend(chunk)\n'),
        (P32, '        result.raw_stdout, result.raw_stderr = bytes(sinks[0]["data"]), bytes(sinks[1]["data"])',
         '        result.raw_stdout, result.raw_stderr = bytes(sinks[0].get("all", sinks[0]["data"])), '
         'bytes(sinks[1].get("all", sinks[1]["data"]))')]),
    ('a hard-linked alias is hashed', F32, '            if problem is None and data.nNumberOfLinks != 1:',
     '            if False:'),
    ('an artifact is hashed while a writer has it open', F32,
     '        share = FILE_SHARE_READ if deny_writers else', '        share = FILE_SHARE_READ | FILE_SHARE_WRITE if deny_writers else'),
    ('a lease can be replaced between its check and its delete', F32,
     '        handle = _open(lexical, GENERIC_READ | DELETE, FILE_SHARE_READ, OPEN_EXISTING, FILE_FLAG_OPEN_REPARSE_POINT)',
     '        handle = _open(lexical, GENERIC_READ | DELETE, FILE_SHARE_READ | FILE_SHARE_DELETE, OPEN_EXISTING, FILE_FLAG_OPEN_REPARSE_POINT)'),
    ('a lease is created over an existing entry', F32,
     '            handle = _open(lexical, GENERIC_WRITE | FILE_READ_ATTRIBUTES, FILE_SHARE_READ, CREATE_NEW,',
     '            handle = _open(lexical, GENERIC_WRITE | FILE_READ_ATTRIBUTES, FILE_SHARE_READ, OPEN_ALWAYS,'),
    ('a network or mapped drive is accepted', F32, '    if _k32.GetDriveTypeW(str(root)) not in LOCAL_DRIVES:',
     '    if False:'),
    ('an alternate data stream is accepted', F32, '    if ":" in part:', '    if False:'),
    ('a reserved device name is accepted', F32, '    if part.split(".", 1)[0].rstrip(" ").upper() in RESERVED:',
     '    if False:'),
    ('a letter-case variant shares a workspace', F32, '        if exact_last:', '        if False:'),
    ('a batch file or script is started', 'gpos/tools/process.py',
     '    if exe.suffix.lower() != WINDOWS_EXECUTABLE_SUFFIX:', '    if False:'),
    ('a Windows shell or script host is started', 'gpos/tools/process.py',
     '    if exe.name.lower() in WINDOWS_SHELL_EXECUTABLES:', '    if False:'),
    ('a detached process is started on Windows', 'gpos/tools/process.py',
     '    if sys.platform == "win32":   # D3: a Windows supervisor is designed with the Windows Player Runtime, not mapped\n',
     '    if False:\n'),
    ('a Windows-unsafe request id names a workspace', 'gpos/tools/execution.py',
     '        problems += _windows_request_problems(request, adapter_id, cap_id)\n', '        pass\n'),
    ('a Windows workspace creation failure escapes as an exception', 'gpos/tools/execution.py',
     '    except OSError as exc:   # any other refusal of the file system is a structured result too',
     '    except UnicodeError as exc:'),
    ('a Windows output path that is a regular file is not refused', 'gpos/tools/execution.py',
     '    if os.path.lexists(workspace) and not os.path.isdir(workspace):', '    if False:'),
    ('the CLI writes in the ANSI code page', 'gpos/tools/cli.py',
     '    if sys.platform == "win32":\n        _utf8_streams()\n', ''),
    ('the synthetic artifact is written with CRLF', 'gpos/tools/synthetic/helper.py',
     'with open(path, "w", encoding="utf-8", newline="\\n") as fh:', 'with open(path, "w", encoding="utf-8") as fh:'),
    # --- alpha.24: tool discovery on Windows (W09)
    ('Windows discovery searches relative and drive-relative PATH entries', 'gpos/tools/executables.py',
     '        if not entry or not p.drive or len(p.drive) != 2 or not p.root:', '        if not entry:'),
    ('Windows discovery accepts a name with a path separator', 'gpos/tools/executables.py',
     "    if not name or any(c in name for c in '\\\\/:'):", "    if not name:"),
    ('Windows discovery accepts any extension', 'gpos/tools/executables.py',
     '        candidate = os.path.join(entry, exe)\n',
     '        candidate = next((os.path.join(entry, name + x) for x in (".cmd", ".bat", ".exe")\n'
     '                          if os.path.isfile(os.path.join(entry, name + x))), os.path.join(entry, exe))\n'),
] + [(f'the {tool} adapter discovers through shutil.which on Windows', f'gpos/tools/{tool}/adapter.py', DISCOVERY_GUARD, '')
     for tool in ("adb", "blender", "ffmpeg", "ffprobe", "git")]
# Mutations whose tests exercise POSIX-only behaviour (permission bits, sessions, detached processes, the account
# database, killpg): they run on POSIX and are NOT_RUN on Windows, where those tests are explicitly skipped.
POSIX_ONLY = {'the host location follows HOME', 'lease conflict ignored', "another owner's lease is released",
              'timeout ignored', 'environment values copied into provenance', 'symlink escape allowed',
              'path traversal allowed', 'a process-start failure is an opaque defect again',
              'workspace creation failure escapes as an exception', 'public stdout no longer redacted',
              'an output path that is a regular file is not refused',
              'raw buffer bypasses the capture limit', 'the detached-spawn gate is removed',
              'more than one detached process per execution', 'a dry run may start a detached process',
              'a detached spawn skips the boundary rules', 'a detached process shares the caller session',
              'a detached process is never reaped', 'the execution does not re-check the host-location allowlist'}
# Each POSIX-only mutation above edits a POSIX implementation that Windows does not run (alpha.23 guards it); its
# Windows counterpart is a WINDOWS_MUTATIONS entry (the lease, timeout, environment, containment, start-failure,
# redaction and capture-bound twins; the detached-process and host-location refusals). On Windows they are NOT_RUN.
ONLY_ON = {**{m[0]: "WINDOWS" for m in WINDOWS_MUTATIONS}, **{n: "POSIX" for n in POSIX_ONLY}}
SUITES = ("test_tool_foundation.py", "test_windows_foundation.py")


def run(mutation):
    """A mutation is (name, file, anchor, replacement), or (name, [(file, anchor, replacement), ...]) when one
    realistic defect needs more than one edit."""
    name = mutation[0]
    edits = mutation[1] if len(mutation) == 2 else [tuple(mutation[1:])]
    tmp = Path(tempfile.mkdtemp(prefix="gpos-toolmut-"))
    try:
        copy = tmp / "repo"
        shutil.copytree(ROOT, copy, ignore=shutil.ignore_patterns(".git", "__pycache__", ".DS_Store"))
        for rel, anchor, replacement in edits:
            path = copy / rel
            text = gate.read(path)
            if text.count(anchor) != 1:
                return name, f"NOT APPLIED ({rel}: anchor found {text.count(anchor)} times)"
            gate.write(path, text.replace(anchor, replacement))
        for suite in SUITES:   # the foundation suite, then the Windows mechanisms (all skipped on other hosts)
            try:
                out = subprocess.run([*gate.PYTHON, "-B", str(copy / "tests" / suite)], capture_output=True, text=True,
                                     env=dict(os.environ, PYTHONDONTWRITEBYTECODE="1"), timeout=900, **gate.ISOLATED)
            except subprocess.TimeoutExpired:
                return name, "CAUGHT"   # a hang is a failure of the suite
            if out.returncode != 0:
                return name, "CAUGHT"
        return name, "MISSED"
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--jobs", type=int, default=4)
    parser.add_argument("--only", help="run only mutations whose name contains this text")
    args = parser.parse_args()
    selected = [m for m in MUTATIONS + WINDOWS_MUTATIONS if not args.only or args.only in m[0]]
    here, elsewhere = gate.for_host(selected, ONLY_ON)
    return gate.qualify(run, here, args.jobs, not_run=elsewhere)


if __name__ == "__main__":
    sys.exit(main())
